### ISSUE TITLE
Error getting biome type

### ISSUE THREAD

**Issue by Tijeran** [Team-RTG/1.9-Realistic-Terrain-Generation#117]
With latest alpha version, game still crashes when using both **RTG** and **Plants Mega Pack** mod, it has something to do with the **biome type**, here is some excerpt:

java.lang.NullPointerException: Exception ticking world
    at net.minecraftforge.common.BiomeDictionary.containsType(BiomeDictionary.java:421)
    at net.minecraftforge.common.BiomeDictionary.isBiomeOfType(BiomeDictionary.java:242)
    at plantmegapack.habitat.PMPBiomeType.getBiomeType(PMPBiomeType.java:69)
    at plantmegapack.worldgen.PMPWorldgenHelper.isAdjacentToDifferentBiome(PMPWorldgenHelper.java:150)
    at plantmegapack.worldgen.PMPWorldgenSpawn.getHabitatFromPosition(PMPWorldgenSpawn.java:168)
    at plantmegapack.worldgen.PMPWorldgenSpawn.initSpawnLocation(PMPWorldgenSpawn.java:76)

And the complete crash report:

[http://pastebin.com/REeTKUyw](url)

**Comment by topisani** [comment]
this is fixed in an upcoming release

**Comment by Tijeran** [comment]
Great, keep up with the good work!

**Comment by srs-bsns** [comment]
Is this fixed now?

**Comment by VladimirMangos** [comment]
Not crash for me in this way with minecraft 1.9, forge-12.16.1.1938, planmegapack-1.9.8, RTG-1.9-2.0.0-alpha.4, BiomesOPlenty-1.9-4.0.2.2018

**Comment by whichonespink44** [comment]
Pretty sure this has been fixed in the latest release.
